# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RACTable' do
  use_frameworks!
  pod 'ReactiveObjC','3.1.1'
  pod 'Masonry','1.1.0'
  pod 'AFNetworking', '4.0.0'
  pod 'YTKNetwork','3.0.4'
  pod 'YYKit', '~> 1.0.9' # FPSLabel 依赖
  
  pod 'RxSwift'
  pod 'RxCocoa'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
