# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RACTable' do
  use_frameworks!
  pod 'ReactiveObjC','3.1.1'
  pod 'Masonry','1.1.0'
  pod 'AFNetworking', '4.0.0'
  pod 'YTKNetwork','3.0.4'
  pod 'YYKit', '~> 1.0.9' # FPSLabel 依赖
end
